name: nexio
description: A production-grade Flutter networking runtime for Dio with environments, encryption, isolate parsing, retries, caching, offline queues, transfers, and observability.
version: 0.1.0
homepage: https://syedmubashirali.com
topics:
  - networking
  - dio
  - http
  - cache
  - chucker

platforms:
  android:
  ios:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  chucker_flutter: ^1.9.2
  connectivity_plus: ^7.1.1
  crypto: ^3.0.6
  cryptography: ^2.9.0
  dio: ^5.9.2
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  synchronized: ^3.4.0
  uuid: ^4.5.3
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
