import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:crypto/crypto.dart';
import 'package:path_provider/path_provider.dart';
import 'package:synchronized/synchronized.dart';

import 'cache_config.dart';

/// A cache entry stored by Nexio.
class NexioCacheEntry {
  /// Creates a cache entry.
  ///
  /// Parameters:
  /// - [data] is the decrypted raw response body.
  /// - [statusCode] is the HTTP status code.
  /// - [statusMessage] is the HTTP status message when available.
  /// - [headers] are response headers.
  /// - [createdAt] records when the entry was written.
  /// - [expiresAt] records when the entry becomes invalid.
  const NexioCacheEntry({
    required this.data,
    required this.statusCode,
    required this.statusMessage,
    required this.headers,
    required this.createdAt,
    required this.expiresAt,
  });

  /// Decrypted raw response body.
  final Object? data;

  /// HTTP status code.
  final int? statusCode;

  /// HTTP status message.
  final String? statusMessage;

  /// Response headers.
  final Map<String, List<String>> headers;

  /// Time when this entry was written.
  final DateTime createdAt;

  /// Time when this entry expires.
  final DateTime expiresAt;

  /// Whether this entry is expired.
  bool get isExpired => DateTime.now().isAfter(expiresAt);

  /// Converts this entry to a JSON-safe map.
  Map<String, Object?> toJson() {
    return <String, Object?>{
      'data': data,
      'statusCode': statusCode,
      'statusMessage': statusMessage,
      'headers': headers,
      'createdAt': createdAt.toIso8601String(),
      'expiresAt': expiresAt.toIso8601String(),
    };
  }

  /// Builds a cache entry from [json].
  ///
  /// Parameters:
  /// - [json] is the decoded disk cache object.
  factory NexioCacheEntry.fromJson(Map<String, Object?> json) {
    final headers = <String, List<String>>{};
    final rawHeaders = json['headers'];
    if (rawHeaders is Map) {
      for (final entry in rawHeaders.entries) {
        final key = entry.key.toString();
        final value = entry.value;
        if (value is List) {
          headers[key] = value.map((item) => item.toString()).toList();
        }
      }
    }
    return NexioCacheEntry(
      data: json['data'],
      statusCode: json['statusCode'] is int ? json['statusCode'] as int : null,
      statusMessage: json['statusMessage']?.toString(),
      headers: headers,
      createdAt: DateTime.parse(json['createdAt'].toString()),
      expiresAt: DateTime.parse(json['expiresAt'].toString()),
    );
  }
}

/// Memory and disk cache store used by Nexio.
class NexioCacheStore {
  /// Creates a cache store.
  ///
  /// Parameters:
  /// - [config] controls cache storage behavior.
  NexioCacheStore(this.config);

  /// Cache configuration.
  final CacheConfig config;

  final Lock _lock = Lock();
  final Map<String, NexioCacheEntry> _memory = <String, NexioCacheEntry>{};
  Directory? _directory;

  /// Builds a stable cache key from request inputs.
  ///
  /// Parameters:
  /// - [method] is the HTTP method.
  /// - [url] is the resolved request URL.
  /// - [queryParameters] are request query parameters.
  /// - [data] is the request body.
  /// - [extra] is optional cache namespace data such as remote-config API
  ///   version, country, tenant, or logged-in account id.
  static String buildKey({
    required String method,
    required String url,
    Map<String, Object?>? queryParameters,
    Object? data,
    Object? extra,
  }) {
    final source = jsonEncode(<String, Object?>{
      'method': method.toUpperCase(),
      'url': url,
      'query': _stable(queryParameters),
      'data': _stable(data),
      'extra': _stable(extra),
    });
    return sha256.convert(utf8.encode(source)).toString();
  }

  /// Returns a valid cache entry for [key], or `null`.
  ///
  /// Parameters:
  /// - [key] is the cache key generated by [buildKey].
  Future<NexioCacheEntry?> get(String key) async {
    if (!config.enabled) {
      return null;
    }
    final memoryEntry = _memory[key];
    if (memoryEntry != null) {
      if (!memoryEntry.isExpired) {
        return memoryEntry;
      }
      _memory.remove(key);
    }

    if (!config.enableDiskCache) {
      return null;
    }

    return _lock.synchronized(() async {
      final file = await _fileForKey(key);
      if (!file.existsSync()) {
        return null;
      }
      try {
        final decoded = jsonDecode(await file.readAsString());
        if (decoded is! Map<String, Object?>) {
          return null;
        }
        final entry = NexioCacheEntry.fromJson(decoded);
        if (entry.isExpired) {
          await file.delete();
          return null;
        }
        _putMemory(key, entry);
        return entry;
      } catch (_) {
        await file.delete().catchError((Object _) => file);
        return null;
      }
    });
  }

  /// Stores [entry] for [key].
  ///
  /// Parameters:
  /// - [key] is the cache key generated by [buildKey].
  /// - [entry] is the cache entry to retain.
  Future<void> put(String key, NexioCacheEntry entry) async {
    if (!config.enabled) {
      return;
    }
    if (config.enableMemoryCache) {
      _putMemory(key, entry);
    }
    if (!config.enableDiskCache) {
      return;
    }
    await _lock.synchronized(() async {
      final file = await _fileForKey(key);
      try {
        await file.writeAsString(jsonEncode(entry.toJson()), flush: true);
      } on JsonUnsupportedObjectError {
        return;
      }
    });
  }

  /// Removes expired disk cache files.
  Future<void> cleanupExpired() async {
    if (!config.enableDiskCache) {
      return;
    }
    final directory = await _ensureDirectory();
    await Isolate.run(() {
      final now = DateTime.now();
      for (final entity in directory.listSync()) {
        if (entity is! File || !entity.path.endsWith('.json')) {
          continue;
        }
        try {
          final decoded = jsonDecode(entity.readAsStringSync());
          if (decoded is! Map<String, Object?>) {
            continue;
          }
          final expiresAt = DateTime.parse(decoded['expiresAt'].toString());
          if (now.isAfter(expiresAt)) {
            entity.deleteSync();
          }
        } catch (_) {
          entity.deleteSync();
        }
      }
    });
  }

  /// Clears memory and disk cache.
  Future<void> clear() async {
    _memory.clear();
    if (!config.enableDiskCache) {
      return;
    }
    final directory = await _ensureDirectory();
    if (directory.existsSync()) {
      await directory.delete(recursive: true);
    }
    _directory = null;
  }

  void _putMemory(String key, NexioCacheEntry entry) {
    if (!config.enableMemoryCache) {
      return;
    }
    _memory[key] = entry;
    if (_memory.length > config.maxMemoryEntries) {
      final extra = _memory.length - config.maxMemoryEntries;
      for (final key in _memory.keys.take(extra).toList()) {
        _memory.remove(key);
      }
    }
  }

  Future<File> _fileForKey(String key) async {
    final directory = await _ensureDirectory();
    return File('${directory.path}/$key.json');
  }

  Future<Directory> _ensureDirectory() async {
    final existing = _directory;
    if (existing != null) {
      return existing;
    }
    final root = await getApplicationSupportDirectory();
    final directory = Directory('${root.path}/${config.diskFolderName}');
    if (!directory.existsSync()) {
      directory.createSync(recursive: true);
    }
    _directory = directory;
    return directory;
  }

  static Object? _stable(Object? value) {
    if (value is Map) {
      final entries = value.entries.toList()
        ..sort((a, b) => a.key.toString().compareTo(b.key.toString()));
      return <String, Object?>{
        for (final entry in entries) entry.key.toString(): _stable(entry.value),
      };
    }
    if (value is Iterable) {
      return value.map(_stable).toList();
    }
    if (value is DateTime) {
      return value.toIso8601String();
    }
    if (value is num || value is bool || value is String || value == null) {
      return value;
    }
    return value.toString();
  }
}
